version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chatapp
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      DB_HOST: mysql
      DB_USER: chatuser
      DB_PASSWORD: chatpassword
      DB_NAME: chatapp
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  mysql_data:

